name: api-test

on:
  pull_request_target:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'kind/ok-to-test' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Clean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            rm -rf /root/kubeclipper
      - name: Copy
        uses: appleboy/scp-action@master
        env: 
          HOST: ${{ secrets.CHJ_REMOTE_HOST }}
          USERNAME: root
          PORT: ${{ secrets.CHJ_REMOTE_PORT }}
          KEY: ${{ secrets.CHJ_REMOTE_KEY }}
        with:
          source: "/home/runner/work/kubeclipper/kubeclipper"
          target: "/root/apitest/kubeclipper"
  deploy:
    needs: [build]
    name: Deploy and Run api
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 60m
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            set -e
            sh /root/apitest/api-${{ steps.extract_branch.outputs.branch }}.sh
      - name: Run api
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 120m
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            set -e
            pushd /root/apitest/kubeclipper/github/workspace
            find test/api -name '*.yaml' | xargs gabbi-run 172.20.139.223 --
            echo api-test finished
            fi